ASPLab2/Models/Birth.cs
using System;
using System.Data;
using System.Net.Cache;

namespace ASPLab2.Models
{
    public class Birth
    {
        public DateTime dateOfBirth { get; set; }
        public DateTime dateFuture { get; set; }
        private int _age;
        public string? name { get; set; }
        public int age
        {
            get
            {
                _age = Age();
                return _age;
            }
            set
            {
                _age = value;
            }
        }
        public bool IsValid()
        {
            if(name != null && dateOfBirth < DateTime.Now && dateFuture > DateTime.Now)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        public int Age() 
        {
            int a = Convert.ToInt32(dateFuture.Year - dateOfBirth.Year);
            if (dateOfBirth.Month > dateFuture.Month) 
            {
                a--;
                return a;
            }
            else
            {
                return a;
            }
            
        } 
    }
}

ASPLab2/Models/Calculator.cs
using static ASPLab2.Controllers.CalculatorController;

namespace ASPLab2.Models
{
    public class Calculator
    {
        public Operators? Operator { get; set; }
        public double? a { get; set; }
        public double? b { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case Operators.Add:
                        return "+";                     
                    case Operators.Sub:
                        return "-";
                    case Operators.Mul:
                        return "*";
                    case Operators.Div:
                        return "/";
                    default:
                        return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && a != null && b != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.Add:
                    return (double)(a + b);
                case Operators.Sub:   
                    return (double)(a - b);
                case Operators.Mul:  
                    return (double)(a * b);
                case Operators.Div:  
                    return (double)(a / b);

                default: return double.NaN;
            }
        }
    }
}

ASPLab2/Models/ErrorViewModel.cs
namespace ASPLab2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPLab2/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using ASPLab2.Models;

namespace ASPLab2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult BirthForm()
        {
            return View();
        }
        public IActionResult ResultBirth([FromForm] Birth model)
        {
            if(model.IsValid())
            {
                return View(model);
            }
            return View("CustomError");
        }
    }
}

ASPLab2/Controllers/CalculatorController.cs
using ASPLab2.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPLab2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public enum Operators
        {
            Unknown, Add, Mul, Sub, Div
        }
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
        public IActionResult Form()
        {
            return View();
        }
    }
}

ASPLab2/Controllers/HomeController.cs
using ASPLab2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPLab2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPLab2/Views/Birth/BirthForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
<div class="row justify-content-md-center">
    <div class="col-6">
        <h2>Kalkulator Wieku</h2>
            <form action="ResultBirth" method="post">
            <div class="mb-3">
                <label class="form-label" for="x">Imie</label>
                <input class="form-control" type="text" name="name"/>
            </div>
            <div class="mb-3">
                <label class="form-label" for="y">Data urodzenia</label>
                    <input class="form-control" type="date" name="dateOfBirth" id="dateOfBirth" />
            </div>
                <div class="mb-3">
                    <label class="form-label">Przyszła data</label>
                    <input class="form-control" type="date" name="dateFuture" id="dateFuture" />
                </div>
            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Oblicz</button>
            </div>
        </form>
    </div>
</div>
</div>

ASPLab2/Views/Birth/ResultBirth.cshtml
@model Birth
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h4>Witaj @Model.name, masz @Model.age lat </h4>

ASPLab2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="post">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="a" step="0.00001" id="a" />
                </div>
                <div class="mb-3">
                    <select name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="b" step="0.00001" id="b" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

ASPLab2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>@Model.a @Model.Op @Model.b = @Model.Calculate()</H3>

ASPLab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPLab2/Views/Shared/CustomError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 style="color: red;">Wprowadziłeś niepoprawne dane</h1>

ASPLab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPLab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPLab2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPLab2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Formularz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="BirthForm">Kalkulator wieku</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASPLab2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>